contentColumnType: string
fieldGroup: cdb7901d-dda7-49fd-813f-dac11bd25a12
handle: heroImage
instructions: 'Image for home page underneath main navigation. '
name: 'Hero Image'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:f7540f71-83b7-4f0c-8c4b-6d81a58a0e65'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: true
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:f7540f71-83b7-4f0c-8c4b-6d81a58a0e65'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:f7540f71-83b7-4f0c-8c4b-6d81a58a0e65'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
