enableVersioning: true
handle: portfolio
name: Portfolio
propagationMethod: all
siteSettings:
  a2bb1bcc-fef8-4b82-bb9e-14b043df1da3:
    enabledByDefault: true
    hasUrls: true
    template: portfolio/_entry
    uriFormat: 'portfolio/{slug}'
type: channel
